### PR TITLE
doc: fix confusion about the name of this package

### PR DESCRIPTION
**Pull request by jbrains**
When I tried to install this package, I was confused about whether it was gitlab-cli or git-lab-cli, and so I installed the package gitlab-ci and that didn't install any binaries. I have updated the README to try to reduce confusion for the next person.

### CODE REVIEW

**Comment by jbrains** [comment]
I believe that I have fixed the commit comment, so I don't know why commit-lint-pr is still complaining.

**Comment by vishwanatharondekar** [comment]
I actually wanted gitlab-cli but it was already taken in npm registry. I had created github repo long before I tried publishing on npm. I am not sure I want to take this and still keep the repo name same. That will confuse users. Also renaming repo might not be an option. Give me some time to think about this before taking call to merge or not.

**Comment by jbrains** [comment]
I understand how you got there and your concern. Have you already tried contacting the author of `gitlab-ci` to ask them to abandon their project and give you the name?

**Comment by vishwanatharondekar** [comment]
I had contacted the owner of https://www.npmjs.com/package/gitlab-cli 4 years back. Didn't go well because purpose of both projects were bit different and merging those would have required a lot of work we were not ready for.

**Comment by jbrains** [comment]
You can certainly rename the repository in Github. You might need to spend a few moments to figure out _all_ the various _places_ where you need to change that setting, but it should work.

**Comment by vishwanatharondekar** [comment]
I agree with the confusion part but none of the solutions are foolproof and bring some or the other implication or confusion. I am deciding to go against merging this. This is not solving the issue we have. We can live with what we have right now.

**Pull request closed without merging**
