### PR TITLE
More hub-consistent merge-request method names

### PR DESCRIPTION
**Pull request by stevelacey**
I think these are better, obviously this is a breaking change and you're welcome to ignore me, but these are consistent with hub

### CODE REVIEW

**Comment by vishwanatharondekar** [comment]
@stevelacey I see that commandr has support for alias. https://github.com/tj/commander.js/blob/master/examples/deploy#L27

I think it will be good idea to use that rather than doing these changes.

**Comment by stevelacey** [comment]
@vishwanatharondekar I can add the aliases in but `alias` is normally for adding terser options rather than alternatives – and it makes the help output pretty beefy with the command output listing:

```
merge-request|create-merge-request   blah blah blah
merge-request|open-merge-requests   blah blah blah
```

Also note you can only have one alias per command currently in commander.

I would argue for `merge-request` a better alias would be `mr` and you'd loose that opportunity with this change

**Comment by vishwanatharondekar** [comment]
What you are saying makes sense. As per my information I have some users using this in CI with print option. It will break for them since they are installing from github url. If we had npm and versions earlier we could have changed the version to 2.x and that could have helped maybe. 

I will keep this open for a while to come at conclusion.

**Comment by stevelacey** [comment]
@vishwanatharondekar how about with this legacy aliases patch? Allows them to continue working – but doesn't advertise them in the help output 🙆‍♂️

**Comment by vishwanatharondekar** [comment]
This is so smart and bit ugly (global legacie) that I like it 😄 . Give me some time to test a bit and I will merge. It must be awesome working with you.

**Comment by vishwanatharondekar** [comment]
I am merging this. By the way would it make more sense to add `.alias` in `commandr` as well.

**Comment by stevelacey** [comment]
@vishwanatharondekar what do you mean add `.alias` to `commandr`?

**Comment by vishwanatharondekar** [comment]
I mean a pull request in https://github.com/tj/commander.js

**Comment by stevelacey** [comment]
Yeah they could do with support for multiple aliases, though it’s
non-trivial to add, and I doubt they’d merge the legacy undocumented alias
stuff, it’s too obscure of a use-case

**Pull request merged**
