### PR TITLE
Add EditorConfig

### LINKED ISSUE #3: Add editorconfig
Add an `.editorconfig` file so formatting can be standard across collaborators.

http://editorconfig.org/

### PR DESCRIPTION
**Pull request by beckje01**
Added an editorconfig file and formatted index.js to use spaces.

This fixes #3

### CODE REVIEW

**Comment by vishwanatharondekar** [comment]
I thought that this will happen after I merge other PR. Can you please fix the conflicts here @beckje01 .

**Comment by vishwanatharondekar** [comment]
Tried merging using github web UI.

**Comment by vishwanatharondekar** [comment]
Merged after resolving conflicts.

**Comment by beckje01** [comment]
Thanks

**Pull request merged**
